name: Build Mod

on:
  push:
    branches: ["main", "master"]
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hangupass
          path: build/libs/*.jar
          retention-days: 30

      - name: Upload dev artifact (sources)
        uses: actions/upload-artifact@v4
        with:
          name: hangupass-sources
          path: build/libs/*-sources.jar
          retention-days: 30
